### ISSUE TITLE
The built jar needs to be double-clicked TWICE in order to execute

### ISSUE THREAD

**Issue by NPCTheSBest** [kongkongmao/DOtS#2]
Tested in Java8_111, Windows 10 Home, javaw的进程一闪而过,再次双击后运行良好
还是说只是我电脑的问题...
@jacky8399 求测试QWQ

**Comment by jacky8399** [comment]
Give me a release .jar. I will test it later.

**Comment by NPCTheSBest** [comment]
You have Gradle installed right? Just <gradle build> at the work space directory , you will find the jar in build\libs.

**Comment by NPCTheSBest** [comment]
Ensured that it's only the problem with my PC.
